wiremind/wiremind-helm-charts

charts/pghoard/Chart.yaml
charts/pghoard/templates/crontab-restore-autocheck.yaml
charts/pghoard/values.yaml

fix(pghoard): Rectify restore autocheck Pods label to avoid overlapping when selecting by labels, of course no clash was possible between the Job and ReplicaSet controllers, the metadata.ownerReferences field on the Pod and the pod-template-hash label on the ReplicaSet labelselector prevent that.
feat(pghoard): Make it Possible to customize the restore autocheck cronJob schedule

pghoard: auto-check cronjob

---

charts/clamav/Chart.yaml
charts/clamav/templates/deployment.yaml

This PR will be fix #22 which currently won't allow you to set both the custom config (clamd and freshclam)
**Using the local version for testing:**
```
$ helm template test --namespace test --values https://gist.githubusercontent.com/C123R/c0ae8a5e44205fcd965a9ab70150a7e6/raw/e32f27762afa415486c4e4abff10daef72fe7acc/values.yml  ~/github.com/wiremind-helm-charts/charts/clamav/ | grep volume
volumeMounts:
- name: freshclam-config-volume
- name: clamd-config-volume
volumes:
- name: freshclam-config-volume
- name: clamd-config-volume
```

[clamav] fix for #22, allowing to set both freshclam and clamav custom configs at same time

---

charts/clamav/Chart.yaml
charts/clamav/templates/service.yaml
charts/clamav/values.yaml

adding service annotations to have more control while defining the service types 
**--dry run**
```
apiVersion: v1
kind: Service
metadata:
name: clamav
labels:
app.kubernetes.io/name: clamav
helm.sh/chart: clamav-2.0.0
app.kubernetes.io/instance: clamav
app.kubernetes.io/managed-by: Helm
spec:
type: LoadBalancer
ports:
- port: 3310
targetPort: 3310
protocol: TCP
name: clamavport
selector:
app.kubernetes.io/name: clamav
app.kubernetes.io/instance: clamav
```

adding service annotations to support aws nlb

---

charts/karma/Chart.yaml
charts/karma/templates/servicemonitor.yaml
charts/karma/values.schema.json
charts/karma/values.yaml

This pull request allows to easily enable a [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator) for Karma which is used by the [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) to fetch metrics.

feat(karma): allow configuration of a ServiceMonitor

---

charts/cerebro/Chart.yaml
charts/cerebro/values.schema.json
charts/cerebro/values.yaml

Fix env type
```bash
helm diff upgrade dashboard-es-cerebro wiremind/cerebro --namespace monitoring  -f values/elasticsearch/${ENV}/cerebro-values.yaml --version 1.10.4
Error: Failed to render chart: exit status 1: Error: values don't meet the specifications of the schema(s) in the following chart(s):
cerebro:
- env: Invalid type. Expected: null, given: object
Error: plugin "diff" exited with error
```

fix(json): change schema type for env

---

charts/clamav/Chart.yaml
charts/clamav/templates/hpa.yaml
charts/clamav/values.schema.json

ClamAV chart
fix HPA, the scaleTargetRef kind should be a StatefulSet, there are no deployments in this chart
allow  clamdConfig to be a String for multi-line strings object mapping

Clamav hpa fix, convert HorizontalPodAutoscaler to reference based on StatefulSet

---

charts/cerebro/Chart.yaml
charts/cerebro/templates/_helpers.tpl
charts/cerebro/templates/deployment.yaml
charts/cerebro/templates/serviceaccount.yaml
charts/cerebro/values.schema.json
charts/cerebro/values.yaml

Add the ability for the cerebro Helm Chart to manage a Kubernetes ServiceAccount resource. On certain cloud providers, a ServiceAccount can be directly associated with a cloud provider role. For example, see [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) or [AWS IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). This cloud provider feature is enabled by adding an annotation to the ServiceAccount.
@desaintmartin , @machine424 , @francoisminaud you're listed as maintainers of this chart. I thought I'd mention you here so that you can see and review this. Thanks for your help!

cerebro: add Kubernetes ServiceAccount

---

charts/karma/Chart.yaml
charts/karma/README.md
charts/karma/ci/test-values.yaml
charts/karma/templates/deployment.yaml
charts/karma/values.yaml

- instead of add kthxbye sidecar in alertmanager. add the  kthxbyeSidecar in karma chart. 
- point the alertmanager.uri to alertmanager service and port
-  listen to port 80 as 8080 is already used by karma

feat-kthxbyeSidecar-karma-chart

---

charts/dex/Chart.yaml
charts/dex/templates/ingress.yaml

Some cloud-hosted Kubernetes clusters return the version from `.Capabilities.KubeVersion.Version` that is not SemVer compatible (e.g., `v1.22.6-eks-14c7a48` - not the `v` in front). The `semverCompare` function fails on such versions, so this PR strips the leading V and the trailing pre-release label (which also trips `semverCompare`) before comparing. With version 1.22 rolling out, this becomes important, as it no longer accepts `extensions/v1beta1`.

Fixes Kubernetes version comparison in igress API version computation.

---

charts/cerebro/Chart.yaml
charts/cerebro/values.yaml

The `configFromSecretRef` configuration option addressed in #69 had a typo in `values.yaml`.
This PR updates the example configuration.

Closes #157 fix typo for configFromSecretRef.

---

charts/clamav/Chart.yaml
charts/clamav/values.yaml

https://mailu.io/master/releases.html#mailu-2-0-2023-04-03
> The Mailu project has moved to ghcr.io for hosting the docker images. The images on docker.io will be taken down after this release.
Oldest version on their github repo is 1.9.50:
- https://github.com/mailu/Mailu/pkgs/container/clamav/77893510?tag=1.9
- https://github.com/mailu/Mailu/pkgs/container/clamav/77893510?tag=1.9.50

fix(clamav): use github repo instead of docker, bump to 1.9.50

---

charts/buildkitd/Chart.yaml
charts/buildkitd/values.yaml

Use buildkit version 0.12.1-rootless by default.

chore(buildkitd): version 0.8.1

---

charts/clamav/Chart.yaml
charts/clamav/README.md
charts/clamav/templates/ingress.yaml

The code here upgrades k8s version for `clamav` ingress, minimal k8s version to 1.19 per the deprecation guide.

Upgrade clamav k8s ingress version

---

charts/buildkitd/Chart.yaml
charts/buildkitd/templates/statefulset.yaml

There is a difference between pod level securitycontext and container level.
fsGroup is not defined on pod level.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podsecuritycontext-v1-core
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#securitycontext-v1-core

fix(buildkitd): fsGroup is not declared in schema

---

charts/istio-operator-crds/Chart.yaml

It seems there is no change from 1.17 to 1.18 regarding CRDs.

feat(istio): upgrade istio operator crds to 1.18.2

---

charts/cerebro/Chart.yaml
charts/cerebro/templates/deployment.yaml
charts/cerebro/values.yaml

I noticed the Cerebro chart supports pod level security context values but not at the container level. This should add support for the latter.

Support container level securityContext values for Cerebro

---

charts/druid/Chart.yaml
charts/druid/templates/broker/deployment.yaml

Druid does not handle service loadbalancing
It needs unique pod IP
If we want pod DNS resolution, implement StatefulSet for brokers

fix(druid): broker: do not override host if HPA enabled

---

charts/pythie/Chart.yaml
charts/pythie/templates/pythie-serving-hpa.yaml

autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
See: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

fix(pythie): use autoscaler/v2 API for kube 1.26+

---

charts/clamav/Chart.yaml
charts/clamav/templates/statefulset.yaml
charts/clamav/values.yaml

Implementation of the option to set additional pod annotations with `podAnnotations`. So far only pod labels could be set

fix(clamav): implement ability to specify pod annotations

---

charts/buildkitd/Chart.yaml
charts/buildkitd/templates/configmap.yaml
charts/buildkitd/values.yaml

Changes:
- use 0.13.0-rootless image by default
- log format choice (json or text)
- trace toggle
- opentelemetry metrics & traces export
See: https://github.com/moby/buildkit/releases/tag/v0.13.0

chore(buildkitd): upgrade to 0.13.0

---

charts/clamav/Chart.yaml
charts/clamav/templates/_helpers.tpl
charts/clamav/templates/statefulset.yaml
charts/clamav/values.yaml

I chose the _base version of the image because the previously used MailU version didn't include a database either.
Fixes #325
Fixes #432

fix(clamav): Switch to official clamav image

---

charts/clamav/Chart.yaml
charts/clamav/templates/statefulset.yaml
charts/clamav/values.yaml

This is particularly useful for freshclam, since it uses libcurl and can thus use `https_proxy` for the proxy and `CURL_CA_BUNDLE` for additional/alternate CA certificates.
(While there are proxy-related settings in `freshclam.conf`, it is difficult to configure proxy authentication there, since `HTTPProxyPassword` imposes additional security requirements on the config file, which aren't easily satisfied in a Kubernetes context.)

feat(clamav): Allow specifying extra env vars

---

charts/buildkitd/Chart.yaml
charts/buildkitd/templates/statefulset.yaml
charts/buildkitd/values.yaml

* add lifecycle to statefulset.yaml and values.yaml
add lifecycle to buildkitd - useful for running a pre-stop hook to make sure all build jobs can run to completion before terminating the pod
* add terminationGracePeriodSeconds to statefulset.yaml and values.yaml
useful for making sure lifestyle pre-stop hook has enough time to complete

feat(buildkitd): lifecycle and terminationGracePeriodSeconds

---

charts/karma/Chart.yaml
charts/karma/values.schema.json
charts/karma/values.yaml

```
Helm install failed: values don't meet the specifications of the schema(s) in the following chart(s):
karma:
- serviceAccount.name: Invalid type. Expected: null, given: string
```
This error happens if I use the following values:
```yaml
values:
serviceAccount:
create: false
name: my-service-account
```

Allow setting custom serviceAccount.name

---

charts/clamav/Chart.yaml
charts/clamav/values.yaml

Version 1.4.1 fixes [CVE-2024-20506](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-20506) and hence disallows logfiles that are symlinks. Thus we also have to remove that setting.
Luckily, the output is sent to stdout already, meaning we are actually fixing a bug that caused duplicate log lines.

Update ClamAV to 1.4.1

---

charts/buildkitd/Chart.yaml

See: https://github.com/moby/buildkit/releases/tag/v0.18.2

chore(buildkitd): use version 0.18.2 by default

---

charts/karma/Chart.yaml
charts/karma/templates/deployment.yaml
charts/karma/values.yaml

`containerSecurityContext` was incorrectly rendered in case `kthxbyeSidecar.enabled` was `true` or `sidecarContainers` were specified. In this case it became part of the sidecar definition.
This change also adds `kthxbyeSidecar.securityContext` as a way to specify securityContext for the kthxbye sidecar container.

feat(karma): fix containerSecurityContext and add kthxbyeSidecar.securityContext

---

charts/clamav/Chart.yaml
charts/clamav/README.md
charts/clamav/values.yaml

In #456 I forgot to update the docs to reflect that the container image is now sourced from the official repo, not from MailU.
I didn't update the Chart version on purpose because this PR only updates the docs.

chore(clamav): Update docs to refer to official image

---

charts/clamav/Chart.yaml
charts/clamav/templates/workload.yaml
charts/clamav/values.schema.json
charts/clamav/values.yaml

Currently, ClamAV is always deployed as StatefulSet.
This doesn't make sense when not using a PersistentVolume (which isn't even the deafult) and has the disadvantage of less flexible rollingUpdate.
This commit adds the possibility to use a Deployment instead of a StatefulSet when the persistentVolume is not enabled.
It also adds the possibility to set updateStrategy options via Values.

feat(clamav): Add Deployment alternative

---

charts/chartreuse/Chart.yaml

Chartreus check if the Python package minor version is equal to the Chart version. So we must have the same version.

fix(chartreuse): fix version bump to patch only

---

charts/clamav/Chart.yaml
charts/clamav/templates/workload.yaml
charts/clamav/values.schema.json
charts/clamav/values.yaml

Currently, ClamAV can be deployed as a StatefulSet or a Deployment. This PR introduces the option to deploy ClamAV as a DaemonSet.
Adding a DaemonSet alternative allows ClamAV to run on every Kubernetes node. This can be useful in scenarios where you want to ensure that virus definitions are updated locally on each node, or when node-level scanning is required.

feat(clamav): Add DaemonSet alternative

---

charts/buildkitd/Chart.yaml

See: https://github.com/moby/buildkit/releases/tag/v0.22.0

chore(buildkitd): use version 0.22.0 by default

---

charts/clamav/Chart.yaml
charts/clamav/templates/workload.yaml

Service discovery does not take into account ports from native sidecar containers, so no metrics.
Go back to traditional container for our metrics.

fix(clamav): do not use sidecar container for metrics

---

charts/karma/Chart.yaml
charts/karma/templates/configmap.yaml
charts/karma/templates/deployment.yaml
charts/karma/values.schema.json
charts/karma/values.yaml

This PR introduces a toggle called `.configMap.useFullname` for selecting if the fullname is supposed to be used or not.
ConfigMap is the only resource not respecting the fullname logic which is especially useful if you use the Karma chart as a subchart of a monitoring stack
ConfigMap resource should respect the fullname logic as well. The new toggle `.configMap.useFullname` has been introduced for backwards compatibility.

feat(karma): add toggle for using fullname for configmap

---

charts/clickhouse-operator-crds/.helmignore
charts/clickhouse-operator-crds/Chart.yaml
charts/clickhouse-operator-crds/README.md
charts/clickhouse-operator-crds/templates/CustomResourceDefinition-clickhouseinstallations.clickhouse.altinity.com.yaml
charts/clickhouse-operator-crds/templates/CustomResourceDefinition-clickhouseinstallationtemplates.clickhouse.altinity.com.yaml
charts/clickhouse-operator-crds/templates/CustomResourceDefinition-clickhousekeeperinstallations.clickhouse-keeper.altinity.com.yaml
charts/clickhouse-operator-crds/templates/CustomResourceDefinition-clickhouseoperatorconfigurations.clickhouse.altinity.com.yaml

- Introduced a new CustomResourceDefinition (CRD) for ClickHouseOperatorConfiguration to allow customization of clickhouse-operator settings.
- The CRD includes detailed specifications for various parameters such as watch namespaces, ClickHouse configurations, access settings, and metrics collection.
- Added a new values.yaml file for the clickhouse-operator-crds chart to support the new CRD.

Add CustomResourceDefinition for ClickHouseOperatorConfiguration
