charts/clamav/Chart.yaml, charts/clamav/templates/ingress.yaml
the servicePort in ingress should match the name specified in the service.yaml
=> update clamav ingress servicePort to reflect the port name in clamav

charts/karma/Chart.yaml, charts/karma/ci/test-values.yaml, charts/karma/templates/ingress.yaml, charts/karma/values.yaml
Fixes #42. Note that this drops support for k8s <1.19.
=> [karma] Adopt networking.k8s.io/v1

charts/dex-k8s-authenticator/Chart.yaml, charts/dex-k8s-authenticator/templates/ingress.yaml
Hello,
I've added support for new ingress api versions with conditional checks to keep the old api versions.
=> dex-k8s-authenticator: added support for new ingress api versions

charts/clamav/Chart.yaml, charts/clamav/templates/statefulset.yaml
Hi,
I've put together this small PR to fix an issue with templating the tolerations block as described in #147.
Thanks!
=> Fix up tolerations templating

charts/chartreuse/Chart.yaml, charts/chartreuse/templates/job.yaml, charts/chartreuse/values.schema.json, charts/chartreuse/values.yaml
Added missing fields:
- podAnnotations
- affinity
- tolerations
- nodeSelector
=> feat(chartreuse): add missing fields

charts/kube-prometheus-stack-crds/Chart.yaml, charts/kube-prometheus-stack-crds/templates/crd-alertmanagerconfigs.yaml, charts/kube-prometheus-stack-crds/templates/crd-alertmanagers.yaml, charts/kube-prometheus-stack-crds/templates/crd-podmonitors.yaml, charts/kube-prometheus-stack-crds/templates/crd-probes.yaml, charts/kube-prometheus-stack-crds/templates/crd-prometheuses.yaml, charts/kube-prometheus-stack-crds/templates/crd-prometheusrules.yaml, charts/kube-prometheus-stack-crds/templates/crd-servicemonitors.yaml, charts/kube-prometheus-stack-crds/templates/crd-thanosrulers.yaml
(prometheus operator v0.59.1).
=> feat(kubeprometheusstack): upgrade CRDs to 40.0.0

charts/cerebro/Chart.yaml, charts/cerebro/templates/deployment.yaml, charts/cerebro/templates/secret.yaml
Signed-off-by: Kevin Huang <git@kevin.huang.to>
=> feat(cerebro): Replace configmap with secret

charts/clamav/Chart.yaml, charts/clamav/templates/statefulset.yaml
=> (fix: clamav) Indentation 

charts/cert-manager-crds/Chart.yaml, charts/cert-manager-crds/templates/crd-certificaterequests.yaml, charts/cert-manager-crds/templates/crd-certificates.yaml, charts/cert-manager-crds/templates/crd-challenges.yaml, charts/cert-manager-crds/templates/crd-clusterissuers.yaml, charts/cert-manager-crds/templates/crd-issuers.yaml, charts/cert-manager-crds/templates/crd-orders.yaml
upgrade the cert-manager-crds to the to the newes available Version of cert-manager
=> feat(cert-manager-crds): bump to version 1.9.1

charts/clamav/Chart.yaml, charts/clamav/templates/_helpers.tpl, charts/clamav/templates/serviceaccount.yaml, charts/clamav/templates/statefulset.yaml, charts/clamav/values.yaml
Added customizable serviceaccount with default values of create it, but do not automount it.
=> Added customizable serviceaccount

charts/elasticsearch-cluster/Chart.lock, charts/elasticsearch-cluster/Chart.yaml, charts/elasticsearch-cluster/templates/configmap-setup.yaml
Aslo upgrade elas…ticseach-exporter dependency.
=> fix(elasticsearch): fix ELASTICSEARCH_HOST in setup job

charts/karma/Chart.yaml, charts/karma/templates/service.yaml, charts/karma/values.yaml
Adding `loadBalancerSourceRanges` to karma service
=> adding `loadBalancerSourceRanges` to karma service 

charts/elasticsearch-cluster/Chart.yaml, charts/elasticsearch-cluster/templates/keystore-s3-secret.yaml, charts/elasticsearch-cluster/values.yaml, ct.yaml
- Implement keystore into its own variable
- Changed backup to setup and updated the snapshot strategy ( will be done later if needed )
=> chore(es): Updated Setup

charts/karma/Chart.yaml, charts/karma/templates/deployment.yaml
=> feat: Add priorityClassName to Karma's Deployment

charts/karma/Chart.yaml, charts/karma/templates/deployment.yaml, charts/karma/templates/serviceaccount.yaml, charts/karma/values.yaml
Karma does not require access to the Kubernetes API.
https://hub.armosec.io/docs/c-0034
=> feat(karma): set automountServiceAccountToken to false

charts/buildkitd/Chart.yaml, charts/buildkitd/templates/statefulset.yaml
Fixes bug from a84fb3c70df9b3ebc6c8b0b487e090d5d36d0119
=> fix(buildkitd): remove wrong fieldPath

.github/workflows/lint_test.yml, charts/istio-operator/Chart.yaml, charts/istio-operator/values.yaml
* feat(istio): upgrade crd to 1.18.2.
* feat(istio): upgrade operator to 1.18.2.
See https://istio.io/latest/news/security/istio-security-2023-003/
=> Upgrade istio to 1.18

charts/karma/Chart.yaml, charts/karma/templates/configmap.yaml, charts/karma/templates/deployment.yaml, charts/karma/values.yaml
- add acls setting in configmap
- add hostAliases for pod
=> feat(karma): add acls setting and hostAliases

.github/workflows/lint_test.yml, charts/karma/Chart.yaml, charts/karma/templates/configmap.yaml, charts/karma/templates/ingress.yaml, ct.yaml
#366 
Evaluate following values by tpl function:
```
ingress.annotations
ingress.hosts
ingress.tls[].hosts
configMap.rawConfig
```
=> evaluate some values by tpl function

charts/druid/Chart.yaml, charts/druid/templates/broker/deployment.yaml, charts/druid/templates/broker/hpa.yaml, charts/druid/templates/coordinator/deployment.yaml, charts/druid/templates/historical/hpa.yaml, charts/druid/templates/indexer/deployment.yaml, charts/druid/templates/router/deployment.yaml, charts/druid/templates/router/hpa.yaml, charts/druid/values.yaml
only use DNS resolution with per-pod services (statefulsets)
=> fix(druid): router: capabilities

charts/marge-bot/Chart.yaml, charts/marge-bot/templates/deployment.yaml, charts/marge-bot/values.yaml
https://github.com/hiboxsystems/marge-bot/releases/tag/0.13.0
https://github.com/hiboxsystems/marge-bot/pull/44#issuecomment-1908668856
=> chore(marge-bot): bump app version to 0.13.0

charts/prometheus-safety-exporter/.helmignore, charts/prometheus-safety-exporter/Chart.yaml
Ignore grafana dashboard directory
=> chore(prometheus-safety-exporter): ignore grafana

charts/karma/Chart.yaml, charts/karma/templates/deployment.yaml, charts/karma/templates/service.yaml, charts/karma/templates/serviceaccount.yaml, charts/karma/values.yaml
This change allows to define sidecarContainers, e.g. to inject an oauth proxy.
=> feat: sidecar container

charts/druid/Chart.yaml, charts/druid/templates/coordinator/service.yaml, charts/druid/templates/coordinator/statefulset.yaml, charts/druid/values.yaml
The coordinator do not need autoscaling. For HA, just increase the replicaCount of the statefulset.
=> fix(druid): remove coordinator autoscaling values

charts/elasticsearch-cluster/Chart.yaml, charts/elasticsearch-cluster/values.yaml
…ugins to enable, defaults to repository-s3 and mapper-size.
=> feat(elasticsearch): update to 7.17.22, allow to specify a list of plugins to enable, defaults to repository-s3 and mapper-size.

charts/karma/Chart.yaml, charts/karma/templates/deployment.yaml, charts/karma/values.yaml
The last missing piece to override basicauth credential without storing the whole configuration into a secret.
=> feat: override command args of karma container

charts/clamav/Chart.yaml, charts/clamav/templates/clamd-configmap.yaml, charts/clamav/templates/freshclam-configmap.yaml, charts/clamav/templates/hpa.yaml, charts/clamav/templates/ingress.yaml, charts/clamav/templates/poddisruptionbudget.yaml, charts/clamav/templates/service.yaml, charts/clamav/templates/serviceaccount.yaml, charts/clamav/templates/statefulset.yaml
Fixes https://github.com/wiremind/wiremind-helm-charts/issues/174
=> fix(clamav): follow template best practices

charts/clamav/Chart.yaml, charts/clamav/ci/labels-no-hpa-values.yaml, charts/clamav/templates/statefulset.yaml
Fixes https://github.com/wiremind/wiremind-helm-charts/issues/233
=> fix(clamav): remove version from immutable fields

charts/druid/Chart.yaml, charts/druid/templates/historical/statefulset.yaml
Fixes https://github.com/wiremind/wiremind-helm-charts/issues/529
=> fix(druid-cluster): remove hardcoded default storageClassName

charts/external-dns-crds/Chart.yaml, charts/external-dns-crds/README.md, charts/external-dns-crds/templates/dnsendpoint.yaml
Add CRDs for v0.15.0 (chart version v1.15.0)
=> feat(external-dns-crds): add CRDs

charts/cert-manager-crds/Chart.yaml
Follow-up to 10af15efcbbc6e23e959f4c644985df1efee8db4
=> fix(cert-manager-crds): upgrade chart version

charts/prometheus-safety-exporter/Chart.yaml, charts/prometheus-safety-exporter/templates/configmap.yaml, charts/prometheus-safety-exporter/templates/deployment.yaml, charts/prometheus-safety-exporter/values.yaml
Also modify script to be POSIX compliant
=> fix(prometheus-safety-exporter): add retry

charts/pythie/Chart.yaml, charts/pythie/templates/pythie-serving-deployment.yaml, charts/pythie/values.yaml
to allow usage of private images
=> chore(pythie): add optional imagePullSecrets to pythieServing deployment

charts/external-secrets-crds/Chart.yaml, charts/external-secrets-crds/values.yaml
update values to be equal to the official chart values
=> fix(external-secrets-crds): update values

charts/buildkitd/Chart.yaml, charts/buildkitd/templates/statefulset.yaml, charts/buildkitd/values.yaml
As per subject, I would like to customize the pod annotations.
=> feat(buildkitd): allow to customize pod annotations

charts/karma/Chart.yaml, charts/karma/README.md
I was a bit confused about ASL term, I think it is better to use this.
=> doc(karma): improve license name

.github/workflows/release.yml
=> ci: push Helm Chart to GHCR

.github/workflows/release.yml
@desaintmartin small QoL change here
=> ci: do not attempt to publish existing chart versions

charts/silence-operator/Chart.yaml
https://github.com/giantswarm/silence-operator/releases/tag/v0.13.0
Please make the OCI chart public after merge and release ❤️
=> feat(silence-operator): bump to app version to 0.13.0

charts/silence-operator-crds/Chart.yaml, charts/silence-operator-crds/templates/monitoring.giantswarm.io_silences.yaml
https://github.com/giantswarm/silence-operator/releases/tag/v0.13.0
Please make the OCI chart public after merge and release ❤️
=> feat(silence-operator-crds): bump to app version 0.13.0

charts/karma/Chart.yaml, charts/karma/templates/configmap.yaml, charts/karma/templates/deployment.yaml, charts/karma/templates/ingress.yaml, charts/karma/templates/service.yaml, charts/karma/templates/serviceaccount.yaml, charts/karma/templates/servicemonitor.yaml
several of your other charts already follow this format this gets this chart inline with the others
=> feat(karma): resources have namespace metadata
